name: "Bump Version"

on:
  push:
    branches:
      - "main"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}

      - name: "Output package.sjon before modification"
        run: cat ./package.json

      - name: "Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        # with:
        #   tag-prefix: "v"
        with:
          skip-tag: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Output package.sjon after modification"
        run: cat ./package.json

      # - name: "Output Step"
      #   env:
      #     NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      #   run: echo "new tag $NEW_TAG"
