name: npm bump version

on:
  push:
    branches:
      - "main"

      # jobs:
      #   publish:
      #     ...
      #     permissions:
      #       contents: write

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.4
